export type Tour = { name: string; description: string; image: string; activityId?: string };

/**
 * The 22 tours from insidetoursja.com/tours-excursions/, each paired with its
 * real photo (reconstructed from the live DOM: one <img class="et-waypoint">
 * immediately follows each tour heading, in order). The three tours with a
 * `activityId` are wired to the Yetti booking widget and are sorted first so
 * guests can book them directly; the rest keep the standard enquiry link.
 */
export const tours: Tour[] = [
  { name: "Dunns River Falls Catamaran Cruise Tour", description: "A dynamic tour of our famous falls is a must!, enjoy snorkeling, and live music with drinks on board as your cruise on the Caribbean ocean.", image: "/ingested/insidetoursja/img-045.webp", activityId: "e064a5a4-a62f-4e9b-b2ce-a1fd7629d3c3" },
  { name: "White River Bamboo Rafting Tour", description: "The no. 1 rafting attraction which lasts for 45 minutes to an hour is an experience you would not want to miss!, enjoy the exotic surroundings and the colorful birds as you sit back, relax and enjoy the Caribbean sun as the captain navigates the vibrant and rich river while you raft.", image: "/ingested/insidetoursja/img-049.webp", activityId: "b815fe4f-1846-447e-8bd0-a712aadb7d3c" },
  { name: "White River Tubing Tour", description: "A Fresh, cool river surrounded by tropical scenery is definitely the place to be with the entire family! The tubing which lasts between 45 minutes to an hour is a sight you will never forget with the lush green vegetation on every side you can also have a swim and enjoy the cool river water.", image: "/ingested/insidetoursja/img-056.webp", activityId: "7b5adb04-dc59-4a4e-aee7-0e04fdfad605" },
  { name: "Appleton Estate Rum Tour", description: "Its a fun and historical excursion of how one of our finest rum is made from start to finish, come and participate in exciting activities, and getting to taste the different ages of rum.", image: "/ingested/insidetoursja/img-043.webp" },
  { name: "Bob Marley Nine Mile Tour", description: "A historical tour about a legend, the birthplace of our king of reggae, Bob Marley, come and experience a tour of where he lived and grew up as a child, and get to view his guitars, photographs, and awards! where it's all about a king.", image: "/ingested/insidetoursja/img-044.webp" },
  { name: "Konoko Falls Tour", description: "A place of nature and leisure with friends and families, you'll meet indigenous birds and animals, take a tour through the beautiful gardens, climb the falls and take a swim in the cool and refreshing water.", image: "/ingested/insidetoursja/img-046.webp" },
  { name: "Negril's Day Out", description: "Spend the day on the long 7 miles beach and Margaritaville, relax and enjoy beach activities, while sipping on some cool drinks then take a trip to Rick's cafe to be entertained by live reggae music, the jumping off cliffs, and the beautiful sunset.", image: "/ingested/insidetoursja/img-047.webp" },
  { name: "Ricks Cafe Tour", description: "One of the most famous attractions and top bars in the world is a fun and exciting place to visit with great music and dancing, a magnificent view of the sunset, and heart throbbing cliff jumping.", image: "/ingested/insidetoursja/img-048.webp" },
  { name: "ATVs Adventure Tour", description: "Take an exciting ride into the dirt coast of Jamaica's ground, an adventure that is fun-filled and memorable, take a ride down the trails of sweet Jamaica with inside tours of Jamaica.", image: "/ingested/insidetoursja/img-050.webp" },
  { name: "Dune Buggy Tour", description: "Enjoy the breathtaking sceneries as you explore nature's beauty on the Wet and Dirty adventure tour, a fun-filled and thrilling experience you don't want to miss.", image: "/ingested/insidetoursja/img-051.webp" },
  { name: "Fishing Trips", description: "Excited about catching fish? Come and get an opportunity to reel in your impressive catch, with a lot of fun and excitement, as you relax and free your mind with beer and water aboard.", image: "/ingested/insidetoursja/img-052.webp" },
  { name: "Local Day Out", description: "Take a bite into some of our delicious local meals for breakfast and lunch, take a walk into our market try local fruits, and meet some of our very own people.", image: "/ingested/insidetoursja/img-053.webp" },
  { name: "Pelican Bar Tour", description: "Come and visit the Pelican bar with sweet outdoor vibes, located in the middle of the sea, this Gem is one of a kind and a great experience for the entire family, the food is great and not to mention the red stripe beer or the Jamaican rum.", image: "/ingested/insidetoursja/img-054.webp" },
  { name: "Scotchies Jerk Centre", description: "The most famous for its jerk chicken and pork, come and get a taste of Jamaica's best for lunch, along with a red stripe or drink of your choice.", image: "/ingested/insidetoursja/img-055.webp" },
  { name: "Zipline Over Dunn's River Falls Tour", description: "A Memorable and thrilling experience as you enjoy the breathtaking view of the waterfalls, the tropical scenery from a different angle, and the nice cool Jamaican breeze as you move from 1 end to the other.", image: "/ingested/insidetoursja/img-057.webp" },
  { name: "Black River Safari Tour", description: "Enjoy a cruise down Jamaica's largest river, get to see Crocodiles of all sizes, explore the lush vegetation, and mangroves and view exotic birds as you journey along.", image: "/ingested/insidetoursja/img-058.webp" },
  { name: "Dunn's River Falls Tour", description: "Most famous falls in Jamaica! A climb into the cool, refreshing water is one of the best experiences you'll always remember. The fall is 180 ft high and 600 ft long, surrounded by lush green vegetation which makes the tour more breathtaking.", image: "/ingested/insidetoursja/img-059.webp" },
  { name: "Horseback Riding in the Ocean", description: "Come and experience the thrill of riding the horses in the ocean, it is definitely a memorable and fun experience with the friendly horses in the nice, cool, and blue ocean.", image: "/ingested/insidetoursja/img-060.webp" },
  { name: "Luminous Lagoon Tour", description: "At night the lagoons glisten and sparkle making it as beautiful as ever, a swim into the lagoons would even make it better and fun-filled, you would not want to miss this exciting adventure.", image: "/ingested/insidetoursja/img-061.webp" },
  { name: "Rafting on the Martha Brae Tour", description: "Enjoy a safe and relaxing cruise down the cool river, watching the leaves and trees being tossed to and fro by the wind as you gently ride your way down, sipping on a nice cold red stripe beer you can then quickly dive in and enjoy the refreshing water.", image: "/ingested/insidetoursja/img-062.webp" },
  { name: "The Blue Hole Tour", description: "A spectacular place for swimming, swinging, hiking and jumping! it is a friendly environment, with beautiful and unforgettable scenery.", image: "/ingested/insidetoursja/img-063.webp" },
  { name: "YS Falls Tour", description: "A Mesmerizing experience, an attraction for the whole family! Come and experience the seven falls that cascade into beautiful, natural pools which are great for swimming!", image: "/ingested/insidetoursja/img-064.webp" },
];
